name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./build.sh

      - name: Collect Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: build